# Generated by Django 4.2.2 on 2023-06-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Administrator"), (2, "Curator"), (3, "User")],
                null=True,
            ),
        ),
    ]
