# Generated by Django 4.2.2 on 2023-06-14 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("add_article", "Can add article"),
                    ("update_article", "Can update article"),
                    ("delete_article", "Can delete article"),
                    ("view_article", "Can view article"),
                ]
            },
        ),
    ]
