# Generated by Django 4.2.5 on 2024-09-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0014_compliancereport_check_authors_affiliation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancereport",
            name="check_contains_funded_by_scoap3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="compliancereport",
            name="check_contains_funded_by_scoap3_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
