# Generated by Django 4.2.5 on 2024-09-23 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0015_compliancereport_check_contains_funded_by_scoap3_and_more"),
        ("articles", "0016_compliancereport_check_required_file_formats_and_more"),
    ]

    operations = []
