# Generated by Django 4.2.16 on 2025-05-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0019_compliancereport_check_contains_funded_by_scoap3_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="articleidentifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identifier_type", "DOI")),
                fields=("identifier_value",),
                name="unique_doi_identifier",
            ),
        ),
    ]
