# Generated by Django 4.2.16 on 2025-03-10 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0020_historicalarticlefile"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalArticle",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("reception_date", models.DateField(blank=True, null=True)),
                ("acceptance_date", models.DateField(blank=True, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("first_online_date", models.DateField(blank=True, null=True)),
                ("title", models.TextField()),
                ("subtitle", models.TextField(blank=True, default="")),
                ("abstract", models.TextField(blank=True, default="")),
                ("_created_at", models.DateTimeField(blank=True, editable=False)),
                ("_updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical article",
                "verbose_name_plural": "historical articles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
