# Generated by Django 4.2.16 on 2025-03-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0021_historicalarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlefile",
            name="version_id",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalarticlefile",
            name="version_id",
            field=models.TextField(blank=True, default=""),
        ),
    ]
