# Generated by Django 4.2.16 on 2025-04-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0020_alter_affiliation_author_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationinfo",
            name="material",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
