name: Backend tests

on:
  workflow_call:
    inputs:
      ref:
        description: The reference to test
        type: string
        required: true
      image:
        description: The name of the image to test
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      opensearch:
        image: registry.cern.ch/cern-sis/scoap3/opensearch
        env:
          bootstrap.memory_lock: true
          ES_JAVA_OPTS: -Xms1024m -Xmx1024m
          discovery.type: single-node
          DISABLE_SECURITY_PLUGIN: true
        ports:
          - 9200:9200
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
      redis:
        image: redis:6
        ports:
          - 6379:6379
      db:
        image: postgres:14.1
        env:
          POSTGRES_DB: scoap3
          POSTGRES_USER: scoap3
          POSTGRES_PASSWORD: scoap3
        ports:
          - 5432:5432
      mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
          - '8025:8025'


    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Create index
        run: >
          docker run
          --pull always
          --network=host
          --entrypoint poetry
          --env DJANGO_SETTINGS_MODULE=config.settings.test
          --env DISABLE_SECURITY_PLUGIN=true
          --env POSTGRES_DB=scoap3
          --env POSTGRES_USER=scoap3
          --env POSTGRES_PASSWORD=scoap3
          --env POSTGRES_HOST=127.0.0.1
          --env OPENSEARCH_HOST=127.0.0.1:9200
          ${{ inputs.image }}
          run python manage.py opensearch index --force create
      - name: Test
        run: >
          docker run
          --pull always
          --network=host
          --entrypoint poetry
          --env DJANGO_SETTINGS_MODULE=config.settings.test
          --env DISABLE_SECURITY_PLUGIN=true
          --env POSTGRES_DB=scoap3
          --env POSTGRES_USER=scoap3
          --env POSTGRES_PASSWORD=scoap3
          --env POSTGRES_HOST=127.0.0.1
          --env OPENSEARCH_HOST=127.0.0.1:9200
          ${{ inputs.image }}
          run pytest
