name: Build

on:
  workflow_call:
    inputs:
      ref:
        description: The reference to build
        type: string
        required: true
      image:
        description: The name of the image to build
        type: string
        required: true
      context:
        description: The context used to build the image
        type: string
        required: true
      stage:
        description: The stage to build
        type: string
        required: false
      dockerfile:
        description: The path to the Dockerfile
        type: string
        required: false
    outputs:
      image-id:
        description: The ID of image that has been built
        value: ${{ jobs.build.outputs.image-id }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-id: ${{ steps.uncached.outputs.imageid }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Docker
        uses: cern-sis/gh-workflows/.github/actions/docker-setup@v6.1.0

      - name: Generate image name
        shell: bash
        run: echo "IMAGE=registry.cern.ch/cern-sis/scoap3/scoap3-backend" >>$GITHUB_ENV

      - name: Generate metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: registry.cern.ch
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_SECRET }}

      - name: Build and export
        id: uncached
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          target: ${{ inputs.stage }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          file: ${{ inputs.dockerfile }}
          no-cache: true
