name: Pull request main

on:
  pull_request:
    branches: [main]
    paths-ignore: [ "docs/**" ]

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  test:
    needs: pre-commit
    uses: ./.github/workflows/pr-tests.yml
