---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: scoap3-backend-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200G
  storageClassName: meyrin-cephfs
